import React, { useEffect, useState } from 'react';
import { MainComponent } from './components/main-component/main-component';
import { useGetQuestionsQuery } from './__generated__/queries';
import { Question } from './__generated__/types';


export const Component = () => {

    //** Here is the hook that autogenerated from queries.graphql file */
    const $questions = useGetQuestionsQuery();

    // Ready for usage state
    const [questions, setQuestions] = useState<Question[]>($questions.data?.questions as Question[]);

    useEffect(() => {
        if (!$questions.loading && $questions.data) {
            setQuestions($questions.data.questions as Question[]);
        }
    }, [$questions.data]);

    return (
        <>
            <MainComponent />
            { questions && questions.map(question => {
                return <div style={ { width: 400, height: 400, color: "000000" } }>{ question.text }</div>;
            }) }
        </>
    );
};
